definitions:
  models.User:
    properties:
      addressId:
        items:
          type: string
        type: array
      approved:
        type: string
      cart:
        items:
          type: string
        type: array
      confirmpassword:
        type: string
      customerId:
        type: string
      dateAdded:
        type: string
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      rewards:
        type: string
      status:
        type: string
      telephone:
        type: string
      transactionpoints:
        type: integer
      username:
        type: string
    type: object
host: localhost:3=8071
info:
  contact:
    email: swiggyb1010@datascience.manipal.edu
    name: Aman Gupta
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BuyItNow User Service
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: When a request is made to the / endpoint, if the service is running,
        it returns "Okay"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Checks whether the service is up & running
      tags:
      - Health
  /customers:
    post:
      consumes:
      - application/json
      description: creates a customer account when the admin is verified
      parameters:
      - description: customer details
        in: body
        name: Customer
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: creates a customer account
      tags:
      - Admin
  /customers/{id}:
    delete:
      consumes:
      - application/json
      description: deletes The Customer Details based on the given ID
      parameters:
      - description: customer details
        in: body
        name: Customer
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: deletes a customer account
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: fetches the details of a customer based on the given ID
      parameters:
      - description: customer id
        in: path
        name: CustomerID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: fetches a customer account by ID
      tags:
      - Admin
    put:
      consumes:
      - application/json
      description: Updates The Customer Details
      parameters:
      - description: customer id
        in: path
        name: CustomerID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Updates a customer account
      tags:
      - Admin
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
