node {
     def app
  
     stage('Clone repository') {
            checkout scm
    }

    stage('Build image') {
         sh 'cd admin-service'
        app = docker.build("immadiuttej/admin-service")
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'git') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
}
