node {
     def app
  
     stage('Build') {
           git branch: 'Admin_Service', url: 'https://github.com/swiggy-2022-bootcamp/cdp-team3.git'
          sh 'cd admin-service'
          app = docker.build("immadiuttej/admin-service")
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'git') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
}
