host: localhost:3007
info:
  contact:
    email: swiggyb1010@datascience.manipal.edu
    name: Aman Gupta
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BuyItNow Payment Mode Service
  version: "1.0"
paths:
  /paymentmethods:
    get:
      consumes:
      - application/json
      description: fetches the available payment methods on the portal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: String
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: fetches all the available payment methods
      tags:
      - Payment Method
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
