definitions:
  errors.HTTPErrorDTO:
    properties:
      code:
        description: Error code
        example: 400
        type: integer
      details:
        description: Detailed Error Messages
        example:
        - Invalid email.
        items:
          type: string
        type: array
      message:
        description: Brief Error Message
        example: Status bad request.
        type: string
    type: object
  responses.MessageResponse:
    properties:
      message:
        description: Message being sent through the DTO
        example: Sample Message
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Health Check Endpoint
      produces:
      - application/json
      responses:
        "200":
          description: Health Check Message.
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "500":
          description: Internal Server Error
      summary: Health Check Endpoint
      tags:
      - Health Check
  /confirm:
    post:
      consumes:
      - application/json
      description: Get an overview of the order from the database.
      produces:
      - application/json
      responses:
        "200":
          description: Order Overview Data
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "500":
          description: Internal Server Error
      summary: Get an overview of the order
      tags:
      - Checkout API
  /confirm/success:
    post:
      consumes:
      - application/json
      description: Webhook hit when Order is successful to clear Cart and Unset Session
        Data.
      produces:
      - application/json
      responses:
        "200":
          description: Cart Cleared message DTO.
          schema:
            $ref: '#/definitions/responses.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.HTTPErrorDTO'
        "500":
          description: Internal Server Error
      summary: Order Successful Webhook
      tags:
      - Checkout API
swagger: "2.0"
