// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: grpcs/shipping_checkout/shipping_checkout.proto

package shipping_checkout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname  string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	City      string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Address1  string `protobuf:"bytes,4,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2  string `protobuf:"bytes,5,opt,name=address2,proto3" json:"address2,omitempty"`
	Countryid uint32 `protobuf:"varint,6,opt,name=countryid,proto3" json:"countryid,omitempty"`
	Postcode  uint32 `protobuf:"varint,7,opt,name=postcode,proto3" json:"postcode,omitempty"`
}

func (x *ShippingAddressResponse) Reset() {
	*x = ShippingAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddressResponse) ProtoMessage() {}

func (x *ShippingAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddressResponse.ProtoReflect.Descriptor instead.
func (*ShippingAddressResponse) Descriptor() ([]byte, []int) {
	return file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingAddressResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *ShippingAddressResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *ShippingAddressResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ShippingAddressResponse) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *ShippingAddressResponse) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *ShippingAddressResponse) GetCountryid() uint32 {
	if x != nil {
		return x.Countryid
	}
	return 0
}

func (x *ShippingAddressResponse) GetPostcode() uint32 {
	if x != nil {
		return x.Postcode
	}
	return 0
}

type ShippingAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShippingAddressID string `protobuf:"bytes,1,opt,name=shippingAddressID,proto3" json:"shippingAddressID,omitempty"`
}

func (x *ShippingAddressRequest) Reset() {
	*x = ShippingAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddressRequest) ProtoMessage() {}

func (x *ShippingAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddressRequest.ProtoReflect.Descriptor instead.
func (*ShippingAddressRequest) Descriptor() ([]byte, []int) {
	return file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingAddressRequest) GetShippingAddressID() string {
	if x != nil {
		return x.ShippingAddressID
	}
	return ""
}

var File_grpcs_shipping_checkout_shipping_checkout_proto protoreflect.FileDescriptor

var file_grpcs_shipping_checkout_shipping_checkout_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x22, 0xd9, 0x01, 0x0a, 0x17, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x46, 0x0a, 0x16, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x44, 0x32, 0x77, 0x0a, 0x08, 0x53, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x6b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x2e, 0x73, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x53,
	0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x1a, 0x5a, 0x18, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescOnce sync.Once
	file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescData = file_grpcs_shipping_checkout_shipping_checkout_proto_rawDesc
)

func file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescGZIP() []byte {
	file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescOnce.Do(func() {
		file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescData)
	})
	return file_grpcs_shipping_checkout_shipping_checkout_proto_rawDescData
}

var file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcs_shipping_checkout_shipping_checkout_proto_goTypes = []interface{}{
	(*ShippingAddressResponse)(nil), // 0: shipping_checkout.ShippingAddressResponse
	(*ShippingAddressRequest)(nil),  // 1: shipping_checkout.ShippingAddressRequest
}
var file_grpcs_shipping_checkout_shipping_checkout_proto_depIdxs = []int32{
	1, // 0: shipping_checkout.Shipping.GetShippingAddress:input_type -> shipping_checkout.ShippingAddressRequest
	0, // 1: shipping_checkout.Shipping.GetShippingAddress:output_type -> shipping_checkout.ShippingAddressResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcs_shipping_checkout_shipping_checkout_proto_init() }
func file_grpcs_shipping_checkout_shipping_checkout_proto_init() {
	if File_grpcs_shipping_checkout_shipping_checkout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShippingAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShippingAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcs_shipping_checkout_shipping_checkout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcs_shipping_checkout_shipping_checkout_proto_goTypes,
		DependencyIndexes: file_grpcs_shipping_checkout_shipping_checkout_proto_depIdxs,
		MessageInfos:      file_grpcs_shipping_checkout_shipping_checkout_proto_msgTypes,
	}.Build()
	File_grpcs_shipping_checkout_shipping_checkout_proto = out.File
	file_grpcs_shipping_checkout_shipping_checkout_proto_rawDesc = nil
	file_grpcs_shipping_checkout_shipping_checkout_proto_goTypes = nil
	file_grpcs_shipping_checkout_shipping_checkout_proto_depIdxs = nil
}
